[package]
name = "raycaster"
version = "0.1.0"
authors = ["Pichau"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.6.0"
glam = { version = "0.15", features = ["mint"]}